/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    news: News;
    'media-galleries': MediaGallery;
    videos: Video;
    coaches: Coach;
    athletes: Athlete;
    'schedule-entries': ScheduleEntry;
    partners: Partner;
    media: Media;
    documents: Document;
    users: User;
    'social-post-queue': SocialPostQueue;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    'media-galleries': MediaGalleriesSelect<false> | MediaGalleriesSelect<true>;
    videos: VideosSelect<false> | VideosSelect<true>;
    coaches: CoachesSelect<false> | CoachesSelect<true>;
    athletes: AthletesSelect<false> | AthletesSelect<true>;
    'schedule-entries': ScheduleEntriesSelect<false> | ScheduleEntriesSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'social-post-queue': SocialPostQueueSelect<false> | SocialPostQueueSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'integration-settings': IntegrationSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'integration-settings': IntegrationSettingsSelect<false> | IntegrationSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      crosspostTelegram: TaskCrosspostTelegram;
      crosspostVk: TaskCrosspostVk;
      transcodeVideo: TaskTranscodeVideo;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Страницы сайта, собираемые из блоков. Slug «glavnaya» — это главная (/).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * ЧПУ-адрес. Оставьте пустым — будет создан из заголовка.
   */
  slug?: string | null;
  status: 'draft' | 'published';
  layout?:
    | (
        | HeroSliderBlock
        | MissionBlock
        | StatisticsBlock
        | LatestNewsBlock
        | CallToActionBlock
        | TimelineBlock
        | RulesListBlock
        | TeamGridBlock
        | ScheduleTableBlock
        | PartnersStripBlock
        | GalleryBlock
        | VideoEmbedBlock
        | FAQAccordionBlock
        | ContactFormBlock
        | EducationProgramBlock
        | ForumChallengeBlock
        | RichTextBlock
      )[]
    | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  ogImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroSliderBlock".
 */
export interface HeroSliderBlock {
  slides?:
    | {
        /**
         * Загрузите видео в разделе «Видео» — оно сожмётся в WebM.
         */
        video?: (number | null) | Video;
        image?: (number | null) | Media;
        heading?: string | null;
        subheading?: string | null;
        ctaLabel?: string | null;
        ctaUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  adaptContrast?: boolean | null;
  /**
   * Как часто листаются слайды (для видео обычно дольше — 10–15 с).
   */
  slideDurationSec?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'heroSlider';
}
/**
 * Загрузите видео любого формата — оно автоматически сожмётся в WebM для слайдера.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface Video {
  id: number;
  title?: string | null;
  /**
   * 0 — не обрезать. Для hero обычно достаточно 8–15 секунд (меньше вес, быстрее транскод).
   */
  trimSeconds?: number | null;
  status?: ('pending' | 'processing' | 'ready' | 'failed') | null;
  progress?: number | null;
  durationSeconds?: number | null;
  webmFilename?: string | null;
  posterFilename?: string | null;
  errorText?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * После загрузки нажмите «Редактировать изображение» (Edit image), чтобы задать фокус-точку и кадрирование — она определяет видимую часть фото на сайте (превью показывается в модальном окне).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Можно оставить пустым — подставится из имени файла / названия при показе.
   */
  alt?: string | null;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MissionBlock".
 */
export interface MissionBlock {
  /**
   * Маленькая подпись над заголовком секции. Если пусто — берётся значение по умолчанию.
   */
  eyebrow?: string | null;
  heading?: string | null;
  text?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mission';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatisticsBlock".
 */
export interface StatisticsBlock {
  /**
   * Маленькая подпись над заголовком секции. Если пусто — берётся значение по умолчанию.
   */
  eyebrow?: string | null;
  heading?: string | null;
  stats?:
    | {
        value: string;
        suffix?: string | null;
        label: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'statistics';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LatestNewsBlock".
 */
export interface LatestNewsBlock {
  /**
   * Маленькая подпись над заголовком секции. Если пусто — берётся значение по умолчанию.
   */
  eyebrow?: string | null;
  heading?: string | null;
  /**
   * По умолчанию 3.
   */
  count?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'latestNews';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  heading?: string | null;
  text?: string | null;
  buttonLabel?: string | null;
  buttonUrl?: string | null;
  style?: ('primary' | 'outline') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'callToAction';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TimelineBlock".
 */
export interface TimelineBlock {
  /**
   * Маленькая подпись над заголовком секции. Если пусто — берётся значение по умолчанию.
   */
  eyebrow?: string | null;
  heading?: string | null;
  events?:
    | {
        year?: string | null;
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'timeline';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RulesListBlock".
 */
export interface RulesListBlock {
  /**
   * Маленькая подпись над заголовком секции. Если пусто — берётся значение по умолчанию.
   */
  eyebrow?: string | null;
  heading?: string | null;
  rules?:
    | {
        title?: string | null;
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'rulesList';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TeamGridBlock".
 */
export interface TeamGridBlock {
  /**
   * Маленькая подпись над заголовком секции. Если пусто — берётся значение по умолчанию.
   */
  eyebrow?: string | null;
  heading?: string | null;
  mode?: ('coaches' | 'athletes') | null;
  showAll?: boolean | null;
  coaches?: (number | Coach)[] | null;
  athletes?: (number | Athlete)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'teamGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coaches".
 */
export interface Coach {
  id: number;
  name: string;
  title?: string | null;
  rank?: string | null;
  photo?: (number | null) | Media;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  specializations?:
    | {
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Привяжите пользователя с ролью «тренер», чтобы он мог редактировать свой профиль и расписание своих групп.
   */
  user?: (number | null) | User;
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Определяет права в CMS.
   */
  role: 'admin' | 'editor' | 'coach';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "athletes".
 */
export interface Athlete {
  id: number;
  name: string;
  photo?: (number | null) | Media;
  birthYear?: number | null;
  weightCategory?: string | null;
  rank?: string | null;
  coach?: (number | null) | Coach;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  achievements?:
    | {
        year?: number | null;
        title: string;
        id?: string | null;
      }[]
    | null;
  parentalConsentObtained?: boolean | null;
  parentalConsentDate?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ScheduleTableBlock".
 */
export interface ScheduleTableBlock {
  /**
   * Маленькая подпись над заголовком секции. Если пусто — берётся значение по умолчанию.
   */
  eyebrow?: string | null;
  heading?: string | null;
  showAll?: boolean | null;
  entries?: (number | ScheduleEntry)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'scheduleTable';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedule-entries".
 */
export interface ScheduleEntry {
  id: number;
  group: string;
  dayOfWeek: 'mon' | 'tue' | 'wed' | 'thu' | 'fri' | 'sat' | 'sun';
  startTime: string;
  endTime?: string | null;
  coach?: (number | null) | Coach;
  hall?: string | null;
  ageGroup?: string | null;
  level?: ('beginner' | 'intermediate' | 'advanced' | 'all') | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PartnersStripBlock".
 */
export interface PartnersStripBlock {
  /**
   * Маленькая подпись над заголовком секции. Если пусто — берётся значение по умолчанию.
   */
  eyebrow?: string | null;
  heading?: string | null;
  showAll?: boolean | null;
  partners?: (number | Partner)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'partnersStrip';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  name: string;
  /**
   * Основной логотип (используется на тёмной теме и в шапке). Если логотип светлый — загрузите тёмную версию ниже.
   */
  logo?: (number | null) | Media;
  /**
   * Вторая версия логотипа для светлой темы (например, тёмная версия, если основной — белый). На светлой теме сайт покажет её вместо основного. Необязательно.
   */
  logoLight?: (number | null) | Media;
  /**
   * Отдельный логотип для страницы партнёров (если нужен другой, чем в шапке). Если не задан — используется основной логотип.
   */
  pageLogo?: (number | null) | Media;
  /**
   * Короткий текст о партнёре — показывается на странице «Партнёры».
   */
  description?: string | null;
  linkType?: ('external' | 'internal' | 'none') | null;
  url?: string | null;
  internalPage?: (number | null) | Page;
  erid?: string | null;
  /**
   * Например: ОАО «РЖД», ИНН 7708503727.
   */
  advertiserInfo?: string | null;
  /**
   * Показывается кликабельной иконкой в конце панели навигации.
   */
  isGeneralPartner?: boolean | null;
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock".
 */
export interface GalleryBlock {
  /**
   * Маленькая подпись над заголовком секции. Если пусто — берётся значение по умолчанию.
   */
  eyebrow?: string | null;
  heading?: string | null;
  images?: (number | Media)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'gallery';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoEmbedBlock".
 */
export interface VideoEmbedBlock {
  /**
   * Маленькая подпись над заголовком секции. Если пусто — берётся значение по умолчанию.
   */
  eyebrow?: string | null;
  title?: string | null;
  provider?: ('youtube' | 'rutube' | 'vk') | null;
  url: string;
  poster?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'videoEmbed';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQAccordionBlock".
 */
export interface FAQAccordionBlock {
  /**
   * Маленькая подпись над заголовком секции. Если пусто — берётся значение по умолчанию.
   */
  eyebrow?: string | null;
  heading?: string | null;
  items?:
    | {
        question: string;
        answer?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faqAccordion';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactFormBlock".
 */
export interface ContactFormBlock {
  /**
   * Маленькая подпись над заголовком секции. Если пусто — берётся значение по умолчанию.
   */
  eyebrow?: string | null;
  heading?: string | null;
  description?: string | null;
  /**
   * По умолчанию «Отправить заявку».
   */
  submitLabel?: string | null;
  recipientEmail?: string | null;
  /**
   * Отображается рядом с обязательным чекбоксом согласия.
   */
  consentText?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contactForm';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EducationProgramBlock".
 */
export interface EducationProgramBlock {
  eyebrow?: string | null;
  heading?: string | null;
  /**
   * Короткое описание под заголовком.
   */
  intro?: string | null;
  /**
   * Документ для кнопки «Скачать программу». Загрузите PDF в разделе «Документы» и выберите здесь. Если не задан — используется файл по умолчанию.
   */
  programFile?: (number | null) | Document;
  showProgramDetails?: boolean | null;
  /**
   * Карточки под кнопкой скачивания (организация, кем принято и т. п.).
   */
  meta?:
    | {
        k?: string | null;
        v?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'educationProgram';
}
/**
 * Файлы для скачивания и просмотра на странице «Документы» (PDF, Word и т. п.).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  /**
   * Название документа, отображается на странице «Документы».
   */
  title?: string | null;
  /**
   * Короткое пояснение — что это за документ (необязательно).
   */
  description?: string | null;
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ForumChallengeBlock".
 */
export interface ForumChallengeBlock {
  eyebrow?: string | null;
  heading?: string | null;
  intro?: string | null;
  showSlides?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'forumChallenge';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock".
 */
export interface RichTextBlock {
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  /**
   * ЧПУ-адрес. Оставьте пустым — будет создан из заголовка.
   */
  slug?: string | null;
  status: 'draft' | 'published';
  publishedAt?: string | null;
  excerpt?: string | null;
  heroImage?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Где новость появилась изначально. От этого зависит обратный постинг (site → соцсети).
   */
  originPlatform?: ('site' | 'telegram' | 'vk') | null;
  isAdvertising?: boolean | null;
  erid?: string | null;
  advertiserInfo?: string | null;
  sources?:
    | {
        platform: 'site' | 'telegram' | 'vk';
        externalId?: string | null;
        url?: string | null;
        rawPayload?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  crosspostTargets?:
    | {
        platform: 'telegram' | 'vk';
        status?: ('pending' | 'sent' | 'failed' | 'skipped') | null;
        remoteUrl?: string | null;
        error?: string | null;
        attempts?: number | null;
        lastAttemptAt?: string | null;
        id?: string | null;
      }[]
    | null;
  needsReviewDuplicate?: boolean | null;
  /**
   * Заполняется дедупликатором для ручной проверки/мержа.
   */
  duplicateOf?: (number | null) | News;
  similarityScore?: number | null;
  imageHash?: string | null;
  mergedFrom?:
    | {
        platform?: ('site' | 'telegram' | 'vk') | null;
        externalId?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-galleries".
 */
export interface MediaGallery {
  id: number;
  title: string;
  /**
   * ЧПУ-адрес. Оставьте пустым — будет создан из заголовка.
   */
  slug?: string | null;
  kind: 'photo' | 'film' | 'interview';
  status: 'draft' | 'published';
  publishedAt?: string | null;
  coverImage?: (number | null) | Media;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Для фотогалереи.
   */
  photos?: (number | Media)[] | null;
  /**
   * Видео не хостим у себя — только ссылки на YouTube / RuTube / VK Video.
   */
  videos?:
    | {
        provider?: ('youtube' | 'rutube' | 'vk') | null;
        url: string;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-post-queue".
 */
export interface SocialPostQueue {
  id: number;
  platform: 'telegram' | 'vk';
  externalId: string;
  receivedAt?: string | null;
  rawText?: string | null;
  normalizedText?: string | null;
  mediaHashes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  url?: string | null;
  rawPayload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status?: ('pending' | 'processed' | 'merged' | 'discarded') | null;
  linkedNewsPost?: (number | null) | News;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  name: string;
  contact: string;
  message?: string | null;
  consent: boolean;
  sourcePage?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'crosspostTelegram' | 'crosspostVk' | 'transcodeVideo';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'crosspostTelegram' | 'crosspostVk' | 'transcodeVideo') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'media-galleries';
        value: number | MediaGallery;
      } | null)
    | ({
        relationTo: 'videos';
        value: number | Video;
      } | null)
    | ({
        relationTo: 'coaches';
        value: number | Coach;
      } | null)
    | ({
        relationTo: 'athletes';
        value: number | Athlete;
      } | null)
    | ({
        relationTo: 'schedule-entries';
        value: number | ScheduleEntry;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'social-post-queue';
        value: number | SocialPostQueue;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  layout?:
    | T
    | {
        heroSlider?: T | HeroSliderBlockSelect<T>;
        mission?: T | MissionBlockSelect<T>;
        statistics?: T | StatisticsBlockSelect<T>;
        latestNews?: T | LatestNewsBlockSelect<T>;
        callToAction?: T | CallToActionBlockSelect<T>;
        timeline?: T | TimelineBlockSelect<T>;
        rulesList?: T | RulesListBlockSelect<T>;
        teamGrid?: T | TeamGridBlockSelect<T>;
        scheduleTable?: T | ScheduleTableBlockSelect<T>;
        partnersStrip?: T | PartnersStripBlockSelect<T>;
        gallery?: T | GalleryBlockSelect<T>;
        videoEmbed?: T | VideoEmbedBlockSelect<T>;
        faqAccordion?: T | FAQAccordionBlockSelect<T>;
        contactForm?: T | ContactFormBlockSelect<T>;
        educationProgram?: T | EducationProgramBlockSelect<T>;
        forumChallenge?: T | ForumChallengeBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
      };
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroSliderBlock_select".
 */
export interface HeroSliderBlockSelect<T extends boolean = true> {
  slides?:
    | T
    | {
        video?: T;
        image?: T;
        heading?: T;
        subheading?: T;
        ctaLabel?: T;
        ctaUrl?: T;
        id?: T;
      };
  adaptContrast?: T;
  slideDurationSec?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MissionBlock_select".
 */
export interface MissionBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  text?: T;
  image?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatisticsBlock_select".
 */
export interface StatisticsBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  stats?:
    | T
    | {
        value?: T;
        suffix?: T;
        label?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LatestNewsBlock_select".
 */
export interface LatestNewsBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  count?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  heading?: T;
  text?: T;
  buttonLabel?: T;
  buttonUrl?: T;
  style?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TimelineBlock_select".
 */
export interface TimelineBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  events?:
    | T
    | {
        year?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RulesListBlock_select".
 */
export interface RulesListBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  rules?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TeamGridBlock_select".
 */
export interface TeamGridBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  mode?: T;
  showAll?: T;
  coaches?: T;
  athletes?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ScheduleTableBlock_select".
 */
export interface ScheduleTableBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  showAll?: T;
  entries?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PartnersStripBlock_select".
 */
export interface PartnersStripBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  showAll?: T;
  partners?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock_select".
 */
export interface GalleryBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  images?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoEmbedBlock_select".
 */
export interface VideoEmbedBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  provider?: T;
  url?: T;
  poster?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQAccordionBlock_select".
 */
export interface FAQAccordionBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactFormBlock_select".
 */
export interface ContactFormBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  description?: T;
  submitLabel?: T;
  recipientEmail?: T;
  consentText?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EducationProgramBlock_select".
 */
export interface EducationProgramBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  intro?: T;
  programFile?: T;
  showProgramDetails?: T;
  meta?:
    | T
    | {
        k?: T;
        v?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ForumChallengeBlock_select".
 */
export interface ForumChallengeBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  intro?: T;
  showSlides?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock_select".
 */
export interface RichTextBlockSelect<T extends boolean = true> {
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  publishedAt?: T;
  excerpt?: T;
  heroImage?: T;
  content?: T;
  originPlatform?: T;
  isAdvertising?: T;
  erid?: T;
  advertiserInfo?: T;
  sources?:
    | T
    | {
        platform?: T;
        externalId?: T;
        url?: T;
        rawPayload?: T;
        id?: T;
      };
  crosspostTargets?:
    | T
    | {
        platform?: T;
        status?: T;
        remoteUrl?: T;
        error?: T;
        attempts?: T;
        lastAttemptAt?: T;
        id?: T;
      };
  needsReviewDuplicate?: T;
  duplicateOf?: T;
  similarityScore?: T;
  imageHash?: T;
  mergedFrom?:
    | T
    | {
        platform?: T;
        externalId?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-galleries_select".
 */
export interface MediaGalleriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  kind?: T;
  status?: T;
  publishedAt?: T;
  coverImage?: T;
  description?: T;
  photos?: T;
  videos?:
    | T
    | {
        provider?: T;
        url?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos_select".
 */
export interface VideosSelect<T extends boolean = true> {
  title?: T;
  trimSeconds?: T;
  status?: T;
  progress?: T;
  durationSeconds?: T;
  webmFilename?: T;
  posterFilename?: T;
  errorText?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coaches_select".
 */
export interface CoachesSelect<T extends boolean = true> {
  name?: T;
  title?: T;
  rank?: T;
  photo?: T;
  bio?: T;
  specializations?:
    | T
    | {
        value?: T;
        id?: T;
      };
  user?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "athletes_select".
 */
export interface AthletesSelect<T extends boolean = true> {
  name?: T;
  photo?: T;
  birthYear?: T;
  weightCategory?: T;
  rank?: T;
  coach?: T;
  bio?: T;
  achievements?:
    | T
    | {
        year?: T;
        title?: T;
        id?: T;
      };
  parentalConsentObtained?: T;
  parentalConsentDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedule-entries_select".
 */
export interface ScheduleEntriesSelect<T extends boolean = true> {
  group?: T;
  dayOfWeek?: T;
  startTime?: T;
  endTime?: T;
  coach?: T;
  hall?: T;
  ageGroup?: T;
  level?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  logoLight?: T;
  pageLogo?: T;
  description?: T;
  linkType?: T;
  url?: T;
  internalPage?: T;
  erid?: T;
  advertiserInfo?: T;
  isGeneralPartner?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-post-queue_select".
 */
export interface SocialPostQueueSelect<T extends boolean = true> {
  platform?: T;
  externalId?: T;
  receivedAt?: T;
  rawText?: T;
  normalizedText?: T;
  mediaHashes?: T;
  url?: T;
  rawPayload?: T;
  status?: T;
  linkedNewsPost?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  name?: T;
  contact?: T;
  message?: T;
  consent?: T;
  sourcePage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  clubName?: string | null;
  tagline?: string | null;
  /**
   * Основной логотип для тёмной темы (обычно светлый). Показывается в шапке, подвале и т. д.
   */
  logo?: (number | null) | Media;
  /**
   * Версия логотипа для светлой темы (обычно тёмная). Если не задан — используется основной.
   */
  logoLight?: (number | null) | Media;
  contacts?: {
    phone?: string | null;
    email?: string | null;
    address?: string | null;
    mapEmbed?: string | null;
  };
  socials?: {
    telegram?: string | null;
    max?: string | null;
    vk?: string | null;
    youtube?: string | null;
    rutube?: string | null;
  };
  generalPartner?: (number | null) | Partner;
  /**
   * Пункты верхнего меню (и списка «Разделы» в подвале). Если у пункта задать вложенные ссылки — он станет выпадающим. Если меню пустое — используется меню по умолчанию.
   */
  navigation?:
    | {
        label: string;
        href: string;
        children?:
          | {
              label: string;
              href: string;
              description?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * «Шапки» списочных страниц (надзаголовок, заголовок, подзаголовок).
   */
  pageHeaders?: {
    news?: {
      eyebrow?: string | null;
      title?: string | null;
      subtitle?: string | null;
    };
    schedule?: {
      eyebrow?: string | null;
      title?: string | null;
      subtitle?: string | null;
    };
    coaches?: {
      eyebrow?: string | null;
      title?: string | null;
      subtitle?: string | null;
    };
    media?: {
      eyebrow?: string | null;
      title?: string | null;
      subtitle?: string | null;
    };
    partners?: {
      eyebrow?: string | null;
      title?: string | null;
      subtitle?: string | null;
    };
    contacts?: {
      eyebrow?: string | null;
      title?: string | null;
      subtitle?: string | null;
    };
  };
  defaultSeo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
  };
  footer?: {
    linksHeading?: string | null;
    contactsHeading?: string | null;
    rightsText?: string | null;
  };
  footerText?: string | null;
  /**
   * Служебные подписи: пустые состояния списков и страница 404.
   */
  uiTexts?: {
    emptyNews?: string | null;
    emptyMedia?: string | null;
    emptyCoaches?: string | null;
    notFoundTitle?: string | null;
    notFoundText?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "integration-settings".
 */
export interface IntegrationSetting {
  id: number;
  telegram?: {
    enabled?: boolean | null;
    botToken?: string | null;
    channelId?: string | null;
    crosspostOnPublish?: boolean | null;
  };
  vk?: {
    enabled?: boolean | null;
    accessToken?: string | null;
    groupId?: string | null;
    confirmationToken?: string | null;
    crosspostOnPublish?: boolean | null;
  };
  deduplication?: {
    enabled?: boolean | null;
    timeWindowMinutes?: number | null;
    similarityThreshold?: number | null;
    reviewLowerBound?: number | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  clubName?: T;
  tagline?: T;
  logo?: T;
  logoLight?: T;
  contacts?:
    | T
    | {
        phone?: T;
        email?: T;
        address?: T;
        mapEmbed?: T;
      };
  socials?:
    | T
    | {
        telegram?: T;
        max?: T;
        vk?: T;
        youtube?: T;
        rutube?: T;
      };
  generalPartner?: T;
  navigation?:
    | T
    | {
        label?: T;
        href?: T;
        children?:
          | T
          | {
              label?: T;
              href?: T;
              description?: T;
              id?: T;
            };
        id?: T;
      };
  pageHeaders?:
    | T
    | {
        news?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              subtitle?: T;
            };
        schedule?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              subtitle?: T;
            };
        coaches?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              subtitle?: T;
            };
        media?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              subtitle?: T;
            };
        partners?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              subtitle?: T;
            };
        contacts?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              subtitle?: T;
            };
      };
  defaultSeo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  footer?:
    | T
    | {
        linksHeading?: T;
        contactsHeading?: T;
        rightsText?: T;
      };
  footerText?: T;
  uiTexts?:
    | T
    | {
        emptyNews?: T;
        emptyMedia?: T;
        emptyCoaches?: T;
        notFoundTitle?: T;
        notFoundText?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "integration-settings_select".
 */
export interface IntegrationSettingsSelect<T extends boolean = true> {
  telegram?:
    | T
    | {
        enabled?: T;
        botToken?: T;
        channelId?: T;
        crosspostOnPublish?: T;
      };
  vk?:
    | T
    | {
        enabled?: T;
        accessToken?: T;
        groupId?: T;
        confirmationToken?: T;
        crosspostOnPublish?: T;
      };
  deduplication?:
    | T
    | {
        enabled?: T;
        timeWindowMinutes?: T;
        similarityThreshold?: T;
        reviewLowerBound?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCrosspostTelegram".
 */
export interface TaskCrosspostTelegram {
  input: {
    postId: string;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCrosspostVk".
 */
export interface TaskCrosspostVk {
  input: {
    postId: string;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskTranscodeVideo".
 */
export interface TaskTranscodeVideo {
  input: {
    videoId: string;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}